// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.ENTER_KEY = 13;

  $(function() {
    console.log(window.app);
    return new window.app.AppView();
  });

}).call(this);
