// Generated by CoffeeScript 1.8.0
(function() {
  describe("App namespace", function() {
    return it("should be devined", function() {
      return expect(Gourmet).toBeDefined();
    });
  });

}).call(this);
