// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.app = window.app || {};

  window.app.TodoView = (function(_super) {
    __extends(TodoView, _super);

    function TodoView() {
      return TodoView.__super__.constructor.apply(this, arguments);
    }

    TodoView.prototype.tagName = 'li';

    TodoView.prototype.template = _.template($('#item-template').html());

    TodoView.prototype.events = {
      'click .toggle': 'togglecompleted',
      'dblclick label': 'edit',
      'click .destroy': 'clear',
      'keypress .edit': 'updateOnEnter',
      'blur .edit': 'close'
    };

    TodoView.prototype.initialize = function() {
      this.listenTo(this.model, 'change', this.render);
      this.listenTo(this.model, 'destroy', this.remove);
      return this.listenTo(this.model, 'visible', this.toggleVisible);
    };

    TodoView.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      this.$el.toggleClass('completed', this.model.get('completed'));
      this.toggleVisible();
      this.$input = this.$('.edit');
      return this;
    };

    TodoView.prototype.toggleVisible = function() {
      return this.$el.toggleClass('hidden', this.isHidden());
    };

    TodoView.prototype.isHidden = function() {
      var isCompleted;
      isCompleted = this.model.get('completed');
      return (!isCompleted && window.app.TodoFilter === 'completed') || (isCompleted && window.app.TodoFilter === 'active');
    };

    TodoView.prototype.togglecompleted = function() {
      return this.model.toggle();
    };

    TodoView.prototype.edit = function() {
      this.$el.addClass('editing');
      return this.$input.focus();
    };

    TodoView.prototype.close = function() {
      var value;
      value = this.$input.val().trim();
      if (value) {
        this.model.save({
          title: value
        });
      } else {
        this.clear();
      }
      return this.$el.removeClass('editing');
    };

    TodoView.prototype.updateOnEnter = function(e) {
      if (e.which === window.app.ENTER_KEY) {
        return this.close();
      }
    };

    TodoView.prototype.clear = function() {
      return this.model.destroy();
    };

    return TodoView;

  })(Backbone.View);

}).call(this);
